[WIP] Akka-http-client support
mdedetrich/stripe-scala pull request #14
Opened 2017-02-04 22:25 UTC by mdedetrich

This PR is for replacing dispatch with akka-http-client. The basics of the library have been migrated, however its still not compiling because I am holding off until #13 is decided

2017-03-20 10:21 UTC, leonardehrenfried commented on src/main/resources/application.conf
> +  fileUploadEndpoint="https://uploads.stripe.com"
I was under the impression that the convention Typesafe config was to use hyphens:

See the following examples:
- https://github.com/typesafehub/config
- https://github.com/akka/akka/blob/master/akka-remote/src/main/resources/reference.conf

2017-03-20 14:30 UTC, mdedetrich commented on src/main/resources/application.conf
> +  fileUploadEndpoint="https://uploads.stripe.com"
Okay my bad, had no idea there were conventions. I will change the config to reflect this

2017-04-28 08:56 UTC, mdedetrich commented
@leonardehrenfried Do you want to quickly review this? All tests are passing

2017-04-28 09:07 UTC, leonardehrenfried commented
Okay, will take a look at the weekend.

On 28 April 2017 at 10:56, Matthew de Detrich <notifications@github.com>
wrote:

> @leonardehrenfried <https://github.com/leonardehrenfried> Do you want to
> quickly review this? All tests are passing
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/mdedetrich/stripe-scala/pull/14#issuecomment-297945800>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAJPMu-Jb9Uy-ARDnc5C5Yg6tw4Cjm1zks5r0anYgaJpZM4L3Tqb>
> .
>

2017-04-28 15:52 UTC, leonardehrenfried requested changes
Whilst I think dispatch is good enough I wouldn't be against moving to akka-http. 

However, I think that the users of the library shouldn't have to know what these things are:

```scala
implicit val system       = ActorSystem()
implicit val materializer = ActorMaterializer()
implicit val http         = Http()
```

Would there be a way to hide these from the API surface and provide default implementations instead? Maybe it could be overridden if someone really cares but I believe the default should be to use the library-provided actor systems and materializers.

2017-04-28 15:52 UTC, leonardehrenfried commented on src/main/resources/application.conf
> +  file-upload-chunk-timeout="5 minutes"
Is 5 minutes a good default timeout?

2017-04-28 19:46 UTC, mdedetrich commented on src/main/resources/application.conf
> +  file-upload-chunk-timeout="5 minutes"
No idea, theoretically you should never hit this timeout, its only the timeout for reading the input stream. Do you have a better idea for a timeout? Else I was thinking of leaving it and if it causes a problem I can always change it later

2017-04-28 19:54 UTC, mdedetrich commented
> Would there be a way to hide these from the API surface and provide default implementations instead? Maybe it could be overridden if someone really cares but I believe the default should be to use the library-provided actor systems and materializers.

I can combine them and then use them as default parameters or I can provide them in the `org.mdedetrich.stripe.Config` object. Typically these are implicits which you would place once in an object and then just use an import to provide them throughout your application.

I am more leaning towards documenting this, as its not hard to understand and its pretty much something that everyone has to do when working with other libraries

2017-04-29 11:28 UTC, leonardehrenfried commented on src/main/resources/application.conf
> +  file-upload-chunk-timeout="5 minutes"
Okay, good point.

2017-04-29 20:20 UTC, leonardehrenfried commented
I think I would be more comfortable if the materializer, the actor system and the Http object would be contained in a single trait/object so the method signature is less cluttered. Also, instantiating this one extra object in order to use the library isn't too much to ask.

If this is addressed, 👍  from me.

2017-04-30 07:10 UTC, mdedetrich commented
> I think I would be more comfortable if the materializer, the actor system and the Http object would be contained in a single trait/object so the method signature is less cluttered. Also, instantiating this one extra object in order to use the library isn't too much to ask.

Is it okay if I do this in a seperate PR as there already is an issue for this, i.e. https://github.com/mdedetrich/stripe-scala/issues/13 ? Otherwise I can do it now, but I am want to get this merged to 0.2.x as soon as I can since I have other work that I want to target 0.2.x

2017-04-30 07:59 UTC, leonardehrenfried commented
Sure, of course.

2017-04-30 16:52 UTC, merged