[#14] Set up fatal warnings compilation flag
mdedetrich/stripe-scala pull request #47
Opened 2019-05-09 18:52 UTC by christobill

2019-05-13 08:29 UTC, mdedetrich requested changes
Great work, just using the wrong optimization setting.

2019-05-13 08:29 UTC, mdedetrich commented on build.sbt
> +  "-opt:l:inline"
This should be `"-opt-inline-from:<sources>"`. See https://github.com/mdedetrich/scalajson/issues/43

2019-05-15 23:23 UTC, christobill commented
Thanks for the feedback! I updated the MR

2019-05-16 08:30 UTC, mdedetrich approved these changes

2019-05-16 08:30 UTC, merged

2019-05-16 08:31 UTC, mdedetrich commented
@christobill Do you need a new version to be released any time soon?

2019-05-19 13:07 UTC, christobill commented
@mdedetrich thanks! I will try to propose (and hopefully merge) some MR before a new release :)